/*
 * bdf.c: a .bdf parser
 */

#include "bdf.h"

int bdf_parse(bdf_font_t *f, FILE *fp){
  bdf_char_t *c;
  bdf_prop_t *p;
  int arg, line = 0, pos = 0;
  char state = bdf_state_none;
  char lbuf[BDF_LINE],
       throwaway[256],
       *tmp;
  if(fp == NULL) return bdf_err_file;

  f->props = NULL;
  f->table = NULL;

  while(fgets(lbuf, BDF_LINE, fp) != NULL){
    switch(state){
      case bdf_state_none:
        if(!LINE_IS("STARTFONT")){
          return bdf_err_font;
        }
        state = bdf_state_font;
        break;
      case bdf_state_font:
        if(LINE_IS("STARTCHAR")){
          state = bdf_state_char;
          c = malloc(sizeof(bdf_char_t));
          c->name = strdup(lbuf+strlen("STARTCHAR "));
          c->x = f->x;
          c->y = f->y;
          c->w = f->w;
          c->h = f->h;
        } else if(LINE_IS("CHARS")){
          GET_ARG();
          f->nchars = arg;
        } else if(LINE_IS("SIZE")){
          GET_ARG();
          f->size = arg;
        } else if(LINE_IS("FONTBOUNDINGBOX")){
          sscanf(
            lbuf, "%s %hhi %hhi %hhi %hhi",
            throwaway,
            &(f->w), &(f->h),
            &(f->x), &(f->y)
          );
        } else if(LINE_IS("STARTPROPERTIES")){
          state = bdf_state_prop;
        } else if(LINE_IS("FONT")){
          f->name = malloc(strlen(lbuf)-strlen("FONT ")-1);
          sscanf(
            lbuf, "%s %s",
            throwaway,
            f->name
          );
        } else if(LINE_IS("ENDFONT")){
          fclose(fp);
          return 0;
        }
        break;
      case bdf_state_prop:
        if(LINE_IS("ENDPROPERTIES")){
          state = bdf_state_font;
        } else {
          p = malloc(sizeof(bdf_prop_t));
          p->name = malloc(strlen(lbuf));
          if((tmp=strchr(lbuf, '"')) != NULL){
            p->str_val = malloc(strlen(lbuf));
            sscanf(lbuf, "%s",
              p->name
            );
            strcpy(p->str_val, lbuf+strlen(p->name)+1);
          } else {
            p->str_val = NULL;
            sscanf(lbuf, "%s %i",
              p->name,
              &(p->int_val)
            );
          }
          HASH_ADD_KEYPTR(hh, f->props, p->name, strlen(p->name), p);
        }
        break;
      case bdf_state_char:
        if(LINE_IS("ENCODING")){
          GET_ARG();
          c->codepoint = arg;
        } else if(LINE_IS("DWIDTH")){
          GET_ARG();
          c->x = arg;
        } else if(LINE_IS("BBX")){
          sscanf(
            lbuf, "%s %hhi %hhi %hhi %hhi",
            throwaway,
            &(c->w), &(c->h),
            &(c->x), &(c->y)
          );
        } else if(LINE_IS("BITMAP")){
          state = bdf_state_btmp;
          line = c->h-1;
          memset(c->bmp, 0, c->w*c->h);
        }
        break;
      case bdf_state_btmp:
        if(LINE_IS("ENDCHAR")){
          state = bdf_state_font;
          HASH_ADD_INT(f->table, codepoint, c);
          continue;
        }
        sscanf(lbuf, "%hhx", &(c->bmp[line--]));
        break;
    }
  }

  fclose(fp);
  return bdf_err_read;
}

int bdf_write(bdf_font_t *f, FILE *fp){
  bdf_prop_t *p, *ptmp;
  bdf_char_t *c, *tmp;
  int i;
  if(fp == NULL) return bdf_err_file;

  fseek(fp, 0, SEEK_SET);

  fprintf(fp, "STARTFONT 2.1\n");
  fprintf(fp, "FONT %s\n", f->name);
  fprintf(fp, "SIZE %i 75 75\n", f->size);
  fprintf(fp, "FONTBOUNDINGBOX %i %i %i %i\n", f->x, f->y, f->w, f->h);
  fprintf(fp, "COMMENT \"Generated by bdfedit, https://github.com/Cubified/bdfedit\"\n");
  fprintf(fp, "STARTPROPERTIES %i\n", HASH_COUNT(f->props));
  HASH_ITER(hh, f->props, p, ptmp){
    if(p->str_val != NULL) fprintf(fp, "%s %s", p->name, p->str_val);
    else fprintf(fp, "%s %i\n", p->name, p->int_val);
  }
  fprintf(fp, "ENDPROPERTIES\n");
  fprintf(fp, "CHARS %i\n", f->nchars);
  HASH_ITER(hh, f->table, c, tmp){
    fprintf(fp, "STARTCHAR %s", c->name);
    fprintf(fp, "ENCODING %i\n", c->codepoint);
    fprintf(fp, "SWIDTH 454 0\n");
    fprintf(fp, "DWIDTH 5 0\n");
    fprintf(fp, "BBX %i %i %i %i\n", c->w, c->h, c->x, c->y);
    fprintf(fp, "BITMAP\n");
    for(i=0;i<c->h;i++){
      fprintf(fp, "%02hhX\n", c->bmp[i]);
    }
    fprintf(fp, "ENDCHAR\n");
  }
  fprintf(fp, "ENDFONT\n");

  fclose(fp);
  return 0;
}
